# Content

1. https://stackoverflow.com/questions/55719276/linear-regression-on-each-column-without-creating-for-loops-or-functions

2. https://stackoverflow.com/questions/55718982/extract-xml-to-pandas-dataframe-with-unknown-number-of-nodes

 https://stackoverflow.com/questions/55719276/linear-regression-on-each-column-without-creating-for-loops-or-functions

In [99]:
import numpy as np
import pandas as pd
from functools import partial
from scipy.stats import linregress

np.random.seed(1997)
df = pd.DataFrame(pd.np.random.rand(100, 10))

df.apply(lambda x: linregress(x, y=df.index), result_type='expand').rename(index={0: 'slope', 1: 
                                                                                  'intercept', 2: 'rvalue', 3:
                                                                                  'p-value', 4:'stderr'})

,0,1,2,3,4,5,6,7,8,9
slope,-8.406563,2.985918,14.651689,-12.288305,0.548100,-4.993342,7.212112,-8.405509,11.239807,-3.423878
intercept,53.358677,48.062283,41.966651,55.653192,49.197692,51.874620,46.091797,53.852788,43.923020,51.187425
rvalue,-0.080954,0.028337,0.140719,-0.124478,0.004984,-0.048920,0.073542,-0.089994,0.114038,-0.032706
p-value,0.423318,0.779579,0.162578,0.217226,0.960747,0.628858,0.467128,0.373233,0.258591,0.746671
stderr,10.455359,10.639700,10.413089,9.894507,11.108115,10.298535,9.879534,9.396627,9.891350,10.569350

https://stackoverflow.com/questions/55718982/extract-xml-to-pandas-dataframe-with-unknown-number-of-nodes

In [100]:
data = """<?xml version = '1.0' encoding = 'UTF-8'?>
<EVENT spec="IDL:com/RfcCallEvents:1.0#Z_BAPI_UPDT_SERV_NOTIFICATION">
   <eventHeader>
      <objectName/>
      <objectKey/>
      <eventName/>
      <eventId/>
   </eventHeader>
   <TAB_DETAIL_DATA>
      <ZNEWFLAG>X</ZNEWFLAG>
      <FENUM>2</FENUM>
      <BAUTL>661-01727</BAUTL>
      <OTEIL/>
      <FECOD>KBB</FECOD>
      <URCOD>B08</URCOD>
      <ZCOMPMDF>A</ZCOMPMDF>
      <ZOPREPL/>
      <ZWRNCOV>LP</ZWRNCOV>
      <ZWRNREF/>
      <ZNEWPS>C07XMAAEJCLD</ZNEWPS>
      <ZOLDPN/>
      <ZOLDPD/>
      <ZOLDPS>C07XMAACJCLD</ZOLDPS>
      <MAILINFECOD/>
      <ZUNITPR/>
      <ZNEWPD/>
      <ZNEWPN/>
      <ZABUSE/>
      <ZRPS>S</ZRPS>
      <ZEXKGB/>
      <ZKGBMM/>
      <ZINSTS>000</ZINSTS>
      <ZACKBB/>
      <ZCHKOVR/>
      <ZSNDB/>
      <ZNOTAFISCAL/>
      <ZCONSGMT/>
      <ZPRTCONS/>
      <ZZRTNTRNO/>
      <ZZRTNCAR/>
      <ZZINSPECT/>
      <ZZPR_OPT/>
   </TAB_DETAIL_DATA>
   <TAB_DETAIL_DATA>
      <ZNEWFLAG>X</ZNEWFLAG>
      <FENUM>1</FENUM>
      <BAUTL>661-01727</BAUTL>
      <OTEIL/>
      <FECOD>KBB</FECOD>
      <URCOD>B08</URCOD>
      <ZCOMPMDF>A</ZCOMPMDF>
      <ZOPREPL/>
      <ZWRNCOV>LP</ZWRNCOV>
      <ZWRNREF/>
      <ZNEWPS>C07XMAAEJCLD</ZNEWPS>
      <ZOLDPN/>
      <ZOLDPD/>
      <ZOLDPS>C07XMAACJCLD</ZOLDPS>
      <MAILINFECOD/>
      <ZUNITPR/>
      <ZNEWPD/>
      <ZNEWPN/>
      <ZABUSE/>
      <ZRPS>S</ZRPS>
      <ZEXKGB/>
      <ZKGBMM/>
      <ZINSTS>000</ZINSTS>
      <ZACKBB/>
      <ZCHKOVR/>
      <ZSNDB/>
      <ZNOTAFISCAL/>
      <ZCONSGMT/>
      <ZPRTCONS/>
      <ZZRTNTRNO/>
      <ZZRTNCAR/>
      <ZZINSPECT/>
      <ZZPR_OPT/>
   </TAB_DETAIL_DATA>
   <TAB_HEADER_DATA>
      <QMNUM>030334920069</QMNUM>
      <ZGSXREF>CONSUMER</ZGSXREF>
      <ZVANTREF>G338005317</ZVANTREF>
      <ZSHIPER/>
      <ZSHPRNO/>
      <ZRVREF/>
      <ZTECHID>4HQ2OD6C19</ZTECHID>
      <ZADREPAIR/>
      <ZZKATR7/>
   </TAB_HEADER_DATA>
</EVENT>"""

In [101]:
import xmltodict

In [102]:
dct = xmltodict.parse(data)

In [103]:
def make_df(name="TAB_DETAIL_DATA", dct=dct):
    df = pd.DataFrame()
    if isinstance(dct['EVENT'][name], list):
        for j in dct['EVENT'][name]:
            _ = pd.DataFrame({'value': [y for x, y in j.items()]}, index=j.keys())
            df = pd.concat([df, _])
    else:
        df = pd.DataFrame({'value': [y for x, y in dct['EVENT'][name].items()]}, index=dct['EVENT'][name].keys())
    return df

In [104]:
make_df(name="TAB_HEADER_DATA")

                  value
QMNUM      030334920069
ZGSXREF        CONSUMER
ZVANTREF     G338005317
ZSHIPER            None
ZSHPRNO            None
ZRVREF             None
ZTECHID      4HQ2OD6C19
ZADREPAIR          None
ZZKATR7            None